[env]
AR_aarch64-linux-android = "aarch64-linux-android-ar"
CC_aarch64-linux-android = "aarch64-linux-android28-clang"
CXX_aarch64-linux-android = "aarch64-linux-android28-clang++"
AR_x86_64-linux-android = "x86_64-linux-android-ar"
CC_x86_64-linux-android = "x86_64-linux-android28-clang"
CXX_x86_64-linux-android = "x86_64-linux-android28-clang++"

[target.aarch64-linux-android]
linker = "aarch64-linux-android28-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android28-clang"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
opt-level = 3
overflow-checks = true
panic = "unwind"
rpath = false
strip = "symbols"
